export const PROMPT_MARKER_SIZE = 6;
export const PROMPT_MARKER_HIT_SIZE = 28;
export const PROMPT_SCROLLBAR_RESERVED_WIDTH = 12;
export const PROMPT_MARKER_RAIL_RIGHT = PROMPT_SCROLLBAR_RESERVED_WIDTH;
export const PROMPT_MARKER_RESERVED_RIGHT_LANE =
  PROMPT_SCROLLBAR_RESERVED_WIDTH + PROMPT_MARKER_HIT_SIZE;
